### ISSUE TITLE
IndexError on cloud_sync()

### ISSUE THREAD

**Issue by androm3da** [Storj/cloud-manager#15]
Encountered this failure on `node2`:

```
uploading a candidate: "8513bec_5._Gold.flac"
Traceback (most recent call last):
  File "./cloudsync.py", line 70, in <module>
    cloud.cloud_sync()
  File "/root/pyenv/local/lib/python2.7/site-packages/cloudmanager/cloudmanager.py", line 91, in cloud_sync
    self.RedundancyLevel)
  File "/root/pyenv/local/lib/python2.7/site-packages/plowshare/plowshare.py", line 59, in upload
    return self.multiupload(filename, self.random_hosts(number_of_hosts))
  File "/root/pyenv/local/lib/python2.7/site-packages/plowshare/plowshare.py", line 151, in multiupload
    multiprocessing.dummy.Pool(len(hosts)).map(f, self._hosts_by_success(hosts))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
IndexError: list index out of range
```

Either it's just a problem of the local `settings` on that node or a real bug.

**Comment by EmergentBehavior** [comment]
Could be a parallelization issue too. Maybe one thread/process was trying to access an item in an array that another process had removed?
